version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pg-ht
    environment:
      POSTGRES_DB: ht
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pg-ht:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

volumes:
  pg-ht:
